$(document).ready(function(){
	$("#hide").click(function(){
		$(".title1").hide();
		$(".palm").hide();
		$(".btn").hide();
		$(".quiz1").show();
		$(".question").show();
		$(".btn1").show();
		$(".btn2").show();
		$(".btn3").show();
	});
	$("#answerW").click(function(){
		$(".quiz1").hide();
		$(".question").hide();
		$(".btn1").hide();
		$(".btn2").hide();
		$(".btn3").hide();
		$(".wrong").show();
		$(".btnwrong").show();
	});
	$("#answerW2").click(function(){
		$(".quiz1").hide();
		$(".question").hide();
		$(".btn1").hide();
		$(".btn2").hide();
		$(".btn3").hide();
		$(".wrong").show();
		$(".btnwrong").show();
	});
	$("#answerR").click(function(){
		$(".quiz1").hide();
		$(".question").hide();
		$(".btn1").hide();
		$(".btn2").hide();
		$(".btn3").hide();
		$(".right").show();
		$(".btnwrong").show();
	});
	$("#return").click(function(){
		$(".title1").show();
		$(".palm").show();
		$(".btn").show();
		$(".btnwrong").hide();
		$(".right").hide();
		$(".wrong").hide();
		$(".btn1").hide();
		$(".btn2").hide();
		$(".btn3").hide();
	});
 });